version: '3'

services:
  redis:
    container_name: redis
    image: redis
    ports :
      - "6379:6379"
    volumes :
      - redisstore:/data
    networks:
      - esnet
    deploy:
      placement:
        constraints : [node.role == manager]  

volumes:
  redisstore:
    driver: local

networks:
  esnet:
    driver: overlay

